### ISSUE TITLE
[Steel Thread] Ion 1.1 Draft Macro Support

### ISSUE THREAD

**Issue by almann** [amazon-ion/ion-rust#524]
In the spirit of RFCs, we should have steel-thread of the largest feature proposed in Ion 1.1: ***Macros***.

This is a tracking issue for the various work needed to do this (some GH issues TBD):

- [ ] #519 - Experimental Flag in Cargo.
- [ ] #520 - Efficient Stream API for Ion.
- [ ] #522 - Adds lazy evaluation support.
- [ ] Macro definition parser
- [ ] Macro definition AST
- [ ] Macro definition interpreter (into Stream computation).
- [ ] Text Parser Support for E-Expressions.
- [ ] Binary Parser Support for E-Expressions.
- [ ] Raw/System-level Reader integration for text E-Expressions.
- [ ] Raw/System-level Reader integration for binary E-Expressions.

See the [Ion 1.1 Specification draft][1] for details.

[1]: ﻿https://github.com/amazon-ion/ion-docs/tree/ion-11-specification

**Comment by almann** [comment]
Closing in favor of https://github.com/orgs/amazon-ion/projects/1
