### ISSUE TITLE
TODO for stabilize serde feature

### ISSUE THREAD

**Issue by desaikd** [amazon-ion/ion-rust#646]
There are some improvements needed for serde `experimental` feature to be stabilized. 

- [ ] Add support for SExpression
- [ ] Add configuration option to allow users to choose writer
- [ ] Add more document examples

**Comment by theli-ua** [comment]
imo this should be a blocker for stabilizing as well issues#790
