### ISSUE TITLE
Binary read support for length-prefixed containers

### ISSUE THREAD

**Issue by zslayton** [amazon-ion/ion-rust#664]
* [x] Lists - #769 
* [x] S-expressions - #769 
* [x] Structs
   * [x] `Symbol` field encoding - #768 
   * [x] `FlexSym` field encoding - #768
* [ ] Follow-up to merge Symbol & FlexSym kinds. - #768

**Comment by nirosys** [comment]
Need to follow-up with a PR to merge the separate struct kinds, and handle mid-struct encoding changes.
